#+TITLE: Bootstrapping ByStar, BISOS and Blee
#+DATE: <2024-02-19 Mon 16:27>
#+AUTHOR: Mohsen BANAN
#+OPTIONS: toc:4

The *Libre-Halaal ByStar Digital Ecosystem* (/By* DE/) is an interdisciplinary,
and ethics-oriented non-proprietary digital ecosystem which challenges the
existing proprietary American digital ecosystem while operating concurrently
alongside it. On a global scale, By* provide Internet Application Services which
preserve autonomy and privacy of the individual. *BISOS*: (/By* Internet
Services Operating System/) is a unified and universal framework for developing
both internet services and software-service continuums that use internet
services. BISOS is a layer on top of Debian. *Blee*: (/BISOS Libre-Halaal Emacs
Environment/) is a layer on top of Emacs and BISOS, which creates a
comprehensive integrated usage and development environment. Blee and BISOS are
fully integrated.
See the "*Nature of Polyexistentials*" book available on line at: [[https://github.com/bxplpc/120033][PLPC-120033]]
 for the bigger picture of how all of these fall in a bigger picture.

Here we provide needed instructions for you to create your own BISOS-Site and adopt ByStar.

* Table of Contents     :TOC:
- [[#from-a-fresh-debian-12-or-11-to-raw-bisos][From a Fresh-Debian-12 (or 11) to Raw-BISOS]]
  - [[#start-by-installing-raw-bisos-on-a-fresh-debian-12-or-11][Start By Installing Raw-BISOS on a Fresh-Debian-12 (or 11)]]
  - [[#using-your-raw-bisos][Using Your Raw-BISOS]]
  - [[#summary-of-your-raw-bisos-setup-----what-has-been-installed][Summary of your Raw-BISOS Setup --- What has been Installed]]
- [[#obtaining-a-fresh-debian-for-raw-bisos][Obtaining a Fresh-Debian for Raw-BISOS]]
  - [[#physical-fresh-debian-12-installation][Physical Fresh-Debian-12 Installation]]
  - [[#kvm-fresh-debian-12-installation][KVM Fresh-Debian-12 Installation]]
- [[#using-your-raw-bisos-and-raw-blee-environment-outside-of-bystar][Using Your Raw-BISOS and Raw-Blee Environment Outside of ByStar]]
- [[#about-blee-panels------bystar-bisos-and-blee-are-self-documenting][About Blee-Panels  --- ByStar, BISOS and Blee are self-documenting]]
- [[#building-your-autonomous-bystar-site][Building Your Autonomous ByStar Site]]

* From a Fresh-Debian-12 (or 11) to Raw-BISOS

Raw-BISOS builds on a Fresh-Debian to provide a platform which can then be configured to become
either a usage environment or a service platform.

** Start By Installing Raw-BISOS on a Fresh-Debian-12 (or 11)


On a Fresly installed Debian system  as user intra (or vagrant), run:

#+begin_src sh
wget -q -O - https://raw.githubusercontent.com/bxGenesis/start/main/raw-bisos.sh | tee install-raw-bisos.sh | bash
#+end_src

The downloaded script is saved in "./install-raw-bisos.sh". You can inspect it
    before running it for installation purposes. Feeding to bash has only
    executed the display of a menu.

Choose the last line of thatch, and run:
#+begin_src sh
./install-raw-bisos.sh -h -v -n showRun -i installRawBisos
#+end_src

Respond to the prompts and be patient. Raw-BISOS includes a lot of deb and pip packages.

** Using Your Raw-BISOS

Exit intra user. Login as bystr
The following new top level directories will be created:

** Summary of your Raw-BISOS Setup --- What has been Installed

*** BISOS Base directories

/bisos
/bxo
/de
/var/bisos
/opt/bisosProvisioner

*** Created Accounts And Groups

bisos group
bisos account
bystar account
delimaccount

*** /etc/sudoers

- bisos
  - bystar

*** Py Venvs --- pip packages

    bisos
    bisos/dev
    adopted

*** Deb Pkgs

*** Node Packages
        


* Obtaining a Fresh-Debian for Raw-BISOS

** Physical Fresh-Debian-12 Installation

Link to Panels

** KVM Fresh-Debian-12 Installation

Link to Panels

* Using Your Raw-BISOS and Raw-Blee Environment Outside of ByStar

* About Blee-Panels  --- ByStar, BISOS and Blee are self-documenting

* Building Your Autonomous ByStar Site
